name: Latest Images
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - ".github/workflows/*validate*.yml"
      - "**.md"
      - "flatpaks/**"
      - "system_files/shared/etc/bazaar/**"
  workflow_call:
  workflow_dispatch:

jobs:
  build-image-latest:
    name: Build Latest Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      image_flavors: '["main"]'
      base_names: '["bluefin-dx", "bluefin-cosmic-dx"]'
      stream_name: latest

  generate-release:
    name: Generate Release
    needs: [build-image-latest]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["latest"]'
