name: GTS Images
on:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"
      - ".github/workflows/*iso*.yml"
      - ".github/workflows/*validate*.yml"
      - "iso_files/**"
      - "system_files/shared/etc/bazaar/**"
  schedule:
    - cron: "0 1 * * TUE" # Every Tuesday at 1:00 AM UTC (same as bluefin-lts)
  workflow_dispatch:
  workflow_call:

jobs:
  build-image-gts:
    name: Build GTS Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      # kernel_pin: 6.14.11-200.fc41.x86_64    ## This is where kernels get pinned.
      base_names: '["bluefin", "bluefin-dx", "bluefin-cosmic", "bluefin-cosmic-dx"]'
      stream_name: gts

  generate_release:
    name: Generate Release
    needs: [build-image-gts]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["gts"]'
