name: Beta Images
on:
  merge_group: # Make Beta Images run on merge groups
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"
      - ".github/workflows/*iso*.yml"
      - ".github/workflows/*validate*.yml"
      - "iso_files/**"
      - "system_files/shared/etc/bazaar/**"
  schedule:
    - cron: "50 5 * * 0" # 5:50 UTC sunday
  workflow_call:
  workflow_dispatch:

jobs:
  build-image-beta:
    name: Build Beta Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      base_names: '["bluefin", "bluefin-dx", "bluefin-cosmic", "bluefin-cosmic-dx"]'
      stream_name: beta

  generate-release:
    name: Generate Release
    needs: [build-image-beta]
    secrets: inherit
    uses: ./.github/workflows/generate-release.yml
    with:
      stream_name: '["beta"]'
